/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/feeds/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cities open for browsing
         * @description Only cities with a live area and at least one approved coach in it, busiest first. The head of this list is the sensible default for a visitor who has not chosen.
         */
        get: operations["FeedsController_cities_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/cities/{cityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What coaches in a city have been posting
         * @description Readable signed out. Posts appear here a few hours after they are written, because hiding a reported post needs signed-in reporters and a guest cannot report at all.
         */
        get: operations["FeedsController_cityFeed_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own feed
         * @description Posts from coaches they follow, plus coaches in their city teaching what they said they are looking for. Each post carries a `reason` saying which of the two it is.
         */
        get: operations["FeedsController_myFeed_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/coaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Coaches worth looking at first
         * @description For a signed-in parent with a stated requirement. search_providers() decides who is eligible; the model only orders them and says why. Answers are cached against a fingerprint of the requirement and the candidate set, so a second look is free until one of them changes. Always returns a list where one exists — `ranked: false` means it is in plain distance order, not that anything failed.
         */
        post: operations["SuggestionsController_coaches_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Families worth a coach's attention first
         * @description The same idea pointed the other way, over the coach's demand feed. Not cached: unlike the parent's, this one is asked for deliberately rather than rendered on arrival.
         */
        post: operations["SuggestionsController_students_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CityDto: {
            /** Format: uuid */
            id: string;
            /** @example Indore */
            name: string;
            /** @example Madhya Pradesh */
            state: string | null;
            /** @description Approved coaches serving a live area of this city. */
            coachCount: number;
        };
        FeedPostDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description The coach who wrote it.
             */
            providerId: string;
            displayName: string | null;
            photoUrl: string | null;
            /** @example Sports Academy */
            categoryName: string | null;
            /** @enum {string} */
            kind: "photo" | "video";
            body: string | null;
            /** @description Set when kind is photo. */
            imageUrl: string | null;
            /**
             * @description The 11-character YouTube id. Set when kind is video.
             * @example dQw4w9WgXcQ
             */
            youtubeId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Total, across everyone. */
            likes: number;
            wows: number;
            surprises: number;
            /**
             * @description This caller's own reaction. Absent on the public feed, which has no caller.
             * @enum {string|null}
             */
            myReaction?: "like" | "wow" | "surprise" | null;
            /** @description Whether this caller has already reported it. */
            iReported?: boolean;
            /**
             * @description Why this post is in the feed. 'following' means the caller follows this coach; 'interest' means we suggested them. Absent on the public feed.
             * @enum {string}
             */
            reason?: "following" | "interest";
        };
        CoachSuggestionDto: {
            /** @description A row as search_providers() returns it, passed through unchanged. */
            provider: {
                [key: string]: unknown;
            };
            /** @description Why the model placed this coach here. Null when the list was not ranked. */
            reason: string | null;
        };
        CoachSuggestionsDto: {
            suggestions: components["schemas"]["CoachSuggestionDto"][];
            /** @description False when the list is in plain distance order. */
            ranked: boolean;
            /** @description True when served from the stored ranking. */
            cached?: boolean;
            /**
             * @description Why there is nothing to show; absent when there is. The caller renders these very differently — 'no_requirement' is an invitation to state one, 'not_a_seeker' is not.
             * @enum {string}
             */
            reason?: "not_a_seeker" | "no_requirement" | "no_origin" | "nothing_nearby";
        };
        StudentSuggestionsQueryDto: {
            /**
             * Format: uuid
             * @description The coach's own listing. Must belong to them.
             */
            providerId: string;
            /** Format: uuid */
            serviceCategoryId?: string | null;
            /** Format: uuid */
            areaId?: string | null;
            /** @default 15 */
            radiusKm: number;
        };
        StudentSuggestionDto: {
            /**
             * @description "kind:id" of a demand row.
             * @example seeker:6f1c...
             */
            key: string;
            /** @description Why the model placed it here. */
            reason: string;
        };
        StudentSuggestionsDto: {
            suggestions: components["schemas"]["StudentSuggestionDto"][];
            /**
             * @description Why there is nothing to rank. 'no_demand' also covers too few untouched rows to be worth a model call — the caller keeps showing its own unranked list either way.
             * @enum {string}
             */
            reason?: "not_a_provider" | "no_demand";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    FeedsController_cities_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityDto"][];
                };
            };
        };
    };
    FeedsController_cityFeed_v1: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return posts older than this. Pass the createdAt of the last post you have. */
                before?: string;
            };
            header?: never;
            path: {
                cityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPostDto"][];
                };
            };
        };
    };
    FeedsController_myFeed_v1: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return posts older than this. Pass the createdAt of the last post you have. */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPostDto"][];
                };
            };
        };
    };
    SuggestionsController_coaches_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachSuggestionsDto"];
                };
            };
        };
    };
    SuggestionsController_students_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentSuggestionsQueryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSuggestionsDto"];
                };
            };
        };
    };
}
