/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — the process is up and serving */
        get: operations["HealthController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cities open for browsing
         * @description Only cities with a live area and at least one approved coach in it, busiest first. The head of this list is the sensible default for a visitor who has not chosen.
         */
        get: operations["FeedsController_cities_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/cities/{cityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What coaches in a city have been posting
         * @description Readable signed out. Posts appear here a few hours after they are written, because hiding a reported post needs signed-in reporters and a guest cannot report at all.
         */
        get: operations["FeedsController_cityFeed_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own feed
         * @description Posts from coaches they follow, plus coaches in their city teaching what they said they are looking for. Each post carries a `reason` saying which of the two it is.
         */
        get: operations["FeedsController_myFeed_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is asking, and what they have finished
         * @description The first call after signing in. `role: null` means a verified account that has not chosen a role yet — send them to pick one; it is not an error. The seeker or provider block is present only for that role.
         */
        get: operations["MeController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organisers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own organiser listing
         * @description Null before they have created one — a normal state for an account that has picked the role and not filled the form in yet, not an error. Visible while unapproved, so a company waiting on an admin can see what it submitted.
         */
        get: operations["OrganisersController_mine_v1"];
        /**
         * Create or update it
         * @description One listing per account, so this upserts. Approval and suspension are absent from the body by design and withheld by column privileges besides — naming either is refused by Postgres, not just by this contract.
         */
        put: operations["OrganisersController_save_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queries the caller is party to
         * @description A coach gets the ones raised with them, a parent gets their own. One endpoint for both sides — the row policy decides which rows those are, so neither has to say who it is.
         */
        get: operations["QueriesController_list_v1"];
        put?: never;
        /**
         * Ask a coach to get in touch
         * @description One live query per coach — asking twice returns 400 rather than making a second lead. Needs a completed seeker profile and an approved coach, both enforced by the row policy.
         */
        post: operations["QueriesController_raise_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move a lead along
         * @description The coach's own queries only. callbackAt is required for callback_scheduled.
         */
        patch: operations["QueriesController_setStatus_v1"];
        trace?: never;
    };
    "/api/v1/queries/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply in writing, opening a conversation
         * @description Returns the enquiry to open. If a thread with this family already exists the message lands there instead of starting a second one, and the query is attached to it either way.
         */
        post: operations["QueriesController_answer_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queries/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark it read, for whichever side is asking */
        post: operations["QueriesController_markRead_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cities, areas and the taxonomy, in one call
         * @description Public and cached for a few minutes. Fetch once at startup and keep it — these change only when an admin edits the taxonomy or opens an area. Areas are returned whole, with `isLive` alongside: it gates seekers, not providers, so it is a flag and not a filter.
         */
        get: operations["ReferenceController_all_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/coaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Coaches worth looking at first
         * @description For a signed-in parent with a stated requirement. search_providers() decides who is eligible; the model only orders them and says why. Answers are cached against a fingerprint of the requirement and the candidate set, so a second look is free until one of them changes. Always returns a list where one exists — `ranked: false` means it is in plain distance order, not that anything failed.
         */
        post: operations["SuggestionsController_coaches_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Families worth a coach's attention first
         * @description The same idea pointed the other way, over the coach's demand feed. Not cached: unlike the parent's, this one is asked for deliberately rather than rendered on arrival.
         */
        post: operations["SuggestionsController_students_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CityDto: {
            /** Format: uuid */
            id: string;
            /** @example Indore */
            name: string;
            /** @example Madhya Pradesh */
            state: string | null;
            /** @description Approved coaches serving a live area of this city. */
            coachCount: number;
        };
        FeedPostDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description The coach who wrote it.
             */
            providerId: string;
            displayName: string | null;
            photoUrl: string | null;
            /** @example Sports Academy */
            categoryName: string | null;
            /** @enum {string} */
            kind: "photo" | "video";
            body: string | null;
            /** @description Set when kind is photo. */
            imageUrl: string | null;
            /**
             * @description The 11-character YouTube id. Set when kind is video.
             * @example dQw4w9WgXcQ
             */
            youtubeId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Total, across everyone. */
            likes: number;
            wows: number;
            surprises: number;
            /**
             * @description This caller's own reaction. Absent on the public feed, which has no caller.
             * @enum {string|null}
             */
            myReaction?: "like" | "wow" | "surprise" | null;
            /** @description Whether this caller has already reported it. */
            iReported?: boolean;
            /**
             * @description Why this post is in the feed. 'following' means the caller follows this coach; 'interest' means we suggested them. Absent on the public feed.
             * @enum {string}
             */
            reason?: "following" | "interest";
        };
        MeSeekerDto: {
            name: string | null;
            photoUrl: string | null;
            /** Format: uuid */
            areaId: string | null;
            /** @description Service category ids they said they are looking for. Empty until they say. */
            lookingFor: string[];
            /** @description Whether coaches may approach them. */
            openToOffers: boolean;
        };
        MeProviderDto: {
            /**
             * Format: uuid
             * @description The listing id, which is not the user id.
             */
            id: string;
            displayName: string | null;
            photoUrl: string | null;
            /** @enum {string} */
            providerType: "individual" | "institution" | "event_planner";
            /** @description Visible in search. False means waiting on an admin. */
            approved: boolean;
            /** @description Taken down. Different from never approved, and says so. */
            isSuspended: boolean;
        };
        MeDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Null when the account exists but no role has been chosen.
             * @enum {string|null}
             */
            role: "seeker" | "provider" | "admin" | null;
            /** @description Whether they finished the profile their role requires. */
            profileComplete: boolean;
            phone: string | null;
            /** @description Present only for a seeker. Null when the role is set but the row is not. */
            seeker?: components["schemas"]["MeSeekerDto"] | null;
            /** @description Present only for a provider. */
            provider?: components["schemas"]["MeProviderDto"] | null;
        };
        OrganiserDto: {
            /** Format: uuid */
            id: string;
            name: string | null;
            about: string | null;
            logoUrl: string | null;
            contactEmail: string | null;
            contactPhone: string | null;
            websiteUrl: string | null;
            /** Format: uuid */
            areaId: string | null;
            venueName: string | null;
            venueAddress: string | null;
            /** @description Visible publicly. False means waiting on an admin. */
            approved: boolean;
            /** @description Taken down. Different from never approved, and says so. */
            isSuspended: boolean;
        };
        UpdateOrganiserDto: {
            name?: string;
            about?: string;
            /** Format: uri */
            logoUrl?: string;
            /** Format: email */
            contactEmail?: string;
            /** @example 9876543210 */
            contactPhone?: string;
            /** Format: uri */
            websiteUrl?: string;
            /** Format: uuid */
            areaId?: string;
            venueName?: string;
            venueAddress?: string;
        };
        QueryDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            providerId: string;
            /** @description The coach's name, for the parent's list. */
            providerName: string | null;
            /** Format: uuid */
            seekerId: string;
            /** @description As given when the query was raised, not as the profile reads now. */
            contactName: string;
            /** @description Only ever visible to the two parties. */
            contactPhone: string;
            /** Format: uuid */
            serviceCategoryId: string | null;
            serviceName: string | null;
            details: string | null;
            /** @enum {string} */
            status: "new" | "contacted" | "callback_scheduled" | "completed" | "closed";
            /** Format: date-time */
            callbackAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            respondedAt: string | null;
            /**
             * Format: uuid
             * @description The conversation this query produced, once one exists.
             */
            enquiryId: string | null;
        };
        RaiseQueryDto: {
            /**
             * Format: uuid
             * @description The coach being asked. Must be approved.
             */
            providerId: string;
            contactName: string;
            /**
             * @description Required, unlike on an enquiry. The point of a query is to be called, so one without a number is a request nobody can act on. Prefilled from the profile and editable, so a second number can be used without changing the account.
             * @example +91 98765 43210
             */
            contactPhone: string;
            /** Format: uuid */
            serviceCategoryId?: string;
            details?: string;
        };
        UpdateQueryStatusDto: {
            /** @enum {string} */
            status: "new" | "contacted" | "callback_scheduled" | "completed" | "closed";
            /**
             * Format: date-time
             * @description Required when status is callback_scheduled, ignored otherwise.
             */
            callbackAt?: string;
        };
        AnswerQueryDto: {
            message: string;
        };
        AnsweredQueryDto: {
            /**
             * Format: uuid
             * @description The conversation to open. An existing thread with this family if there was one, so a parent never ends up with two conversations for one coach.
             */
            enquiryId: string;
        };
        CityRefDto: {
            /** Format: uuid */
            id: string;
            /** @example Indore */
            name: string;
            /** @example Madhya Pradesh */
            state: string | null;
        };
        AreaRefDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cityId: string;
            /** @example Vijay Nagar */
            name: string;
            /** @description Centroid, the fallback search origin. */
            lat: number | null;
            lng: number | null;
            /** @description Open to seekers. Providers may register in an area before it opens, so this is a flag rather than a filter — the seeker-facing screens honour it, signup does not. */
            isLive: boolean;
        };
        ServiceCategoryRefDto: {
            /** Format: uuid */
            id: string;
            /** @example Bharatanatyam */
            name: string;
            /**
             * @description One of the eight taxonomy groups. Drives the colour a category renders in.
             * @example dance
             */
            group: string;
        };
        ProviderCategoryRefDto: {
            /** Format: uuid */
            id: string;
            /** @example Dance Teacher */
            name: string;
            /** @enum {string} */
            providerType: "individual" | "institution";
        };
        TeachingPlaceRefDto: {
            /**
             * @description A short text id, not a uuid.
             * @example individual_classes
             */
            id: string;
            /** @example One-to-one */
            label: string;
            description: string | null;
            sortOrder: number;
        };
        ReferenceDto: {
            cities: components["schemas"]["CityRefDto"][];
            areas: components["schemas"]["AreaRefDto"][];
            serviceCategories: components["schemas"]["ServiceCategoryRefDto"][];
            providerCategories: components["schemas"]["ProviderCategoryRefDto"][];
            teachingPlaces: components["schemas"]["TeachingPlaceRefDto"][];
        };
        CoachSuggestionDto: {
            /** @description A row as search_providers() returns it, passed through unchanged. */
            provider: {
                [key: string]: unknown;
            };
            /** @description Why the model placed this coach here. Null when the list was not ranked. */
            reason: string | null;
        };
        CoachSuggestionsDto: {
            suggestions: components["schemas"]["CoachSuggestionDto"][];
            /** @description False when the list is in plain distance order. */
            ranked: boolean;
            /** @description True when served from the stored ranking. */
            cached?: boolean;
            /**
             * @description Why there is nothing to show; absent when there is. The caller renders these very differently — 'no_requirement' is an invitation to state one, 'not_a_seeker' is not.
             * @enum {string}
             */
            reason?: "not_a_seeker" | "no_requirement" | "no_origin" | "nothing_nearby";
        };
        StudentSuggestionsQueryDto: {
            /**
             * Format: uuid
             * @description The coach's own listing. Must belong to them.
             */
            providerId: string;
            /** Format: uuid */
            serviceCategoryId?: string | null;
            /** Format: uuid */
            areaId?: string | null;
            /** @default 15 */
            radiusKm: number;
        };
        StudentSuggestionDto: {
            /**
             * @description "kind:id" of a demand row.
             * @example seeker:6f1c...
             */
            key: string;
            /** @description Why the model placed it here. */
            reason: string;
        };
        StudentSuggestionsDto: {
            suggestions: components["schemas"]["StudentSuggestionDto"][];
            /**
             * @description Why there is nothing to rank. 'no_demand' also covers too few untouched rows to be worth a model call — the caller keeps showing its own unranked list either way.
             * @enum {string}
             */
            reason?: "not_a_provider" | "no_demand";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example 1234 */
                        uptimeSeconds?: number;
                    };
                };
            };
        };
    };
    FeedsController_cities_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityDto"][];
                };
            };
        };
    };
    FeedsController_cityFeed_v1: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return posts older than this. Pass the createdAt of the last post you have. */
                before?: string;
            };
            header?: never;
            path: {
                cityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPostDto"][];
                };
            };
        };
    };
    FeedsController_myFeed_v1: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Return posts older than this. Pass the createdAt of the last post you have. */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedPostDto"][];
                };
            };
        };
    };
    MeController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    OrganisersController_mine_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Null when no listing exists yet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganiserDto"];
                };
            };
        };
    };
    OrganisersController_save_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganiserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganiserDto"];
                };
            };
        };
    };
    QueriesController_list_v1: {
        parameters: {
            query?: {
                status?: "new" | "contacted" | "callback_scheduled" | "completed" | "closed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDto"][];
                };
            };
        };
    };
    QueriesController_raise_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RaiseQueryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                };
            };
        };
    };
    QueriesController_setStatus_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQueryStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                };
            };
        };
    };
    QueriesController_answer_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQueryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnsweredQueryDto"];
                };
            };
        };
    };
    QueriesController_markRead_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReferenceController_all_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceDto"];
                };
            };
        };
    };
    SuggestionsController_coaches_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachSuggestionsDto"];
                };
            };
        };
    };
    SuggestionsController_students_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentSuggestionsQueryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentSuggestionsDto"];
                };
            };
        };
    };
}
